from __future__ import annotations

import json
import hashlib
import re
import sqlite3
from contextlib import closing
from pathlib import Path
from typing import Any, Iterable

from .models import BranchIdentity, CodeReference, ParsedFile, SourceRevision

SCHEMA_VERSION = 4


class ReferenceIdentityConflict(ValueError):
    """Raised when one parser reference id describes conflicting occurrences."""


def _reference_payload(reference: CodeReference) -> tuple[Any, ...]:
    """Return every persisted field that a parser reference id is expected to identify.

    ``reference_id`` is generated by parsers from the source occurrence identity.
    Duplicate emissions of the same occurrence are harmless and are collapsed at
    the storage boundary. Reusing an id for different persisted content is not
    harmless: choosing one row would silently corrupt graph/control-flow evidence,
    so that case is rejected before the existing file occurrence is touched.
    """
    return (
        reference.source_symbol_id or "",
        reference.reference_kind,
        reference.target_name,
        reference.target_qualified_hint,
        int(reference.line),
        int(reference.column),
        reference.source_text,
        tuple(reference.control_context),
    )


def _deduplicate_references(references: Iterable[CodeReference]) -> tuple[list[CodeReference], int]:
    unique: list[CodeReference] = []
    by_id: dict[str, CodeReference] = {}
    duplicate_count = 0
    for reference in references:
        prior = by_id.get(reference.reference_id)
        if prior is None:
            by_id[reference.reference_id] = reference
            unique.append(reference)
            continue
        if _reference_payload(prior) == _reference_payload(reference):
            duplicate_count += 1
            continue
        raise ReferenceIdentityConflict(
            "parser emitted conflicting code references with the same reference_id "
            f"{reference.reference_id}; refusing to choose one occurrence"
        )
    return unique, duplicate_count


def db_path(project_dir: Path) -> Path:
    return project_dir / "index" / "sqlite" / "awoki_code.sqlite"


def manifest_path(project_dir: Path) -> Path:
    return project_dir / "index" / "manifests" / "code-index.json"


def _connect(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    return conn


def _reset_incompatible_database(path: Path) -> None:
    """Discard incompatible derived state instead of carrying migrations forever."""
    if not path.exists():
        return
    with closing(sqlite3.connect(path)) as conn:
        version = int(conn.execute("PRAGMA user_version").fetchone()[0])
        has_schema = bool(conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='code_files'"
        ).fetchone())
    if has_schema and version != SCHEMA_VERSION:
        for candidate in (path, Path(f"{path}-wal"), Path(f"{path}-shm")):
            try:
                candidate.unlink()
            except FileNotFoundError:
                pass


def init_db(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    _reset_incompatible_database(path)
    with closing(_connect(path)) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS code_files (
                file_id TEXT PRIMARY KEY,
                project_id TEXT NOT NULL,
                repo_id TEXT NOT NULL,
                source_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                revision_key TEXT NOT NULL,
                revision_label TEXT NOT NULL,
                content_identity TEXT NOT NULL,
                branch_key TEXT NOT NULL,
                branch_name TEXT NOT NULL,
                commit_sha TEXT NOT NULL,
                dirty INTEGER NOT NULL,
                path TEXT NOT NULL,
                language TEXT NOT NULL,
                content_hash TEXT NOT NULL,
                size_bytes INTEGER NOT NULL,
                parser_id TEXT NOT NULL,
                parse_mode TEXT NOT NULL,
                parse_status TEXT NOT NULL,
                diagnostics_json TEXT NOT NULL,
                indexed_at TEXT NOT NULL,
                UNIQUE(project_id, source_id, revision_key, path)
            );

            CREATE TABLE IF NOT EXISTS code_symbols (
                symbol_id TEXT PRIMARY KEY,
                file_id TEXT NOT NULL REFERENCES code_files(file_id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                qualified_name TEXT NOT NULL,
                kind TEXT NOT NULL,
                parent_symbol_id TEXT,
                start_byte INTEGER NOT NULL,
                end_byte INTEGER NOT NULL,
                start_line INTEGER NOT NULL,
                end_line INTEGER NOT NULL,
                signature TEXT NOT NULL,
                content_hash TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS code_symbols_name_idx ON code_symbols(name);
            CREATE INDEX IF NOT EXISTS code_symbols_qname_idx ON code_symbols(qualified_name);
            CREATE INDEX IF NOT EXISTS code_symbols_file_idx ON code_symbols(file_id);

            CREATE TABLE IF NOT EXISTS code_chunks (
                chunk_id TEXT PRIMARY KEY,
                file_id TEXT NOT NULL REFERENCES code_files(file_id) ON DELETE CASCADE,
                symbol_id TEXT REFERENCES code_symbols(symbol_id) ON DELETE CASCADE,
                symbol_name TEXT NOT NULL,
                qualified_name TEXT NOT NULL,
                symbol_kind TEXT NOT NULL,
                chunk_part INTEGER NOT NULL,
                chunk_total INTEGER NOT NULL,
                start_line INTEGER NOT NULL,
                end_line INTEGER NOT NULL,
                title TEXT NOT NULL,
                text TEXT NOT NULL,
                content_hash TEXT NOT NULL,
                embedding_key TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS code_chunks_embedding_idx ON code_chunks(embedding_key);
            CREATE INDEX IF NOT EXISTS code_chunks_file_idx ON code_chunks(file_id);
            CREATE INDEX IF NOT EXISTS code_chunks_symbol_idx ON code_chunks(symbol_id);

            CREATE VIRTUAL TABLE IF NOT EXISTS code_chunks_fts USING fts5(
                chunk_id UNINDEXED,
                project_id UNINDEXED,
                repo_id UNINDEXED,
                source_id UNINDEXED,
                source_type UNINDEXED,
                revision_key UNINDEXED,
                branch_key UNINDEXED,
                path,
                language,
                symbol_name,
                qualified_name,
                signature,
                text,
                tokenize='unicode61 tokenchars ''./:-'''
            );

            CREATE TABLE IF NOT EXISTS code_references (
                reference_id TEXT PRIMARY KEY,
                file_id TEXT NOT NULL REFERENCES code_files(file_id) ON DELETE CASCADE,
                source_symbol_id TEXT REFERENCES code_symbols(symbol_id) ON DELETE CASCADE,
                reference_kind TEXT NOT NULL,
                target_name TEXT NOT NULL,
                target_qualified_hint TEXT NOT NULL,
                line INTEGER NOT NULL,
                column_no INTEGER NOT NULL,
                source_text TEXT NOT NULL,
                control_context_json TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS code_refs_source_idx ON code_references(source_symbol_id);
            CREATE INDEX IF NOT EXISTS code_refs_target_idx ON code_references(target_name);
            CREATE INDEX IF NOT EXISTS code_refs_kind_idx ON code_references(reference_kind);

            CREATE TABLE IF NOT EXISTS code_edges (
                edge_id TEXT PRIMARY KEY,
                branch_key TEXT NOT NULL,
                source_symbol_id TEXT NOT NULL REFERENCES code_symbols(symbol_id) ON DELETE CASCADE,
                target_symbol_id TEXT REFERENCES code_symbols(symbol_id) ON DELETE CASCADE,
                target_name TEXT NOT NULL,
                edge_kind TEXT NOT NULL,
                line INTEGER NOT NULL,
                confidence TEXT NOT NULL,
                resolution_status TEXT NOT NULL,
                resolution_method TEXT NOT NULL,
                candidate_count INTEGER NOT NULL,
                source_text TEXT NOT NULL,
                control_context_json TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS code_edges_source_idx ON code_edges(branch_key, source_symbol_id);
            CREATE INDEX IF NOT EXISTS code_edges_target_idx ON code_edges(branch_key, target_symbol_id);

            CREATE TABLE IF NOT EXISTS code_index_state (
                branch_key TEXT PRIMARY KEY,
                schema_version INTEGER NOT NULL,
                engine_version TEXT NOT NULL,
                project_id TEXT NOT NULL,
                repo_id TEXT NOT NULL,
                source_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                revision_key TEXT NOT NULL,
                revision_label TEXT NOT NULL,
                content_identity TEXT NOT NULL,
                branch_name TEXT NOT NULL,
                commit_sha TEXT NOT NULL,
                dirty INTEGER NOT NULL,
                source_probe_hash TEXT NOT NULL,
                parser_profile_hash TEXT NOT NULL,
                embedding_profile_hash TEXT NOT NULL,
                document_set_hash TEXT NOT NULL,
                qdrant_membership_hash TEXT NOT NULL,
                indexed_at TEXT NOT NULL,
                vector_status TEXT NOT NULL,
                vector_reason TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS code_vector_memberships (
                project_id TEXT NOT NULL,
                branch_key TEXT NOT NULL,
                embedding_key TEXT NOT NULL,
                chunk_id TEXT NOT NULL,
                content_hash TEXT NOT NULL,
                text TEXT NOT NULL,
                repo_id TEXT NOT NULL,
                source_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                revision_key TEXT NOT NULL,
                content_identity TEXT NOT NULL,
                path TEXT NOT NULL,
                symbol_id TEXT NOT NULL,
                symbol_name TEXT NOT NULL,
                qualified_name TEXT NOT NULL,
                symbol_kind TEXT NOT NULL,
                language TEXT NOT NULL,
                start_line INTEGER NOT NULL,
                end_line INTEGER NOT NULL,
                commit_sha TEXT NOT NULL,
                dirty INTEGER NOT NULL,
                PRIMARY KEY(project_id, branch_key, embedding_key, chunk_id)
            );
            CREATE INDEX IF NOT EXISTS code_vector_memberships_branch_idx
                ON code_vector_memberships(project_id, branch_key);
            """
        )
        conn.execute(f"PRAGMA user_version={SCHEMA_VERSION}")
        conn.commit()


def _revision_fields(branch: BranchIdentity | SourceRevision) -> dict[str, Any]:
    if isinstance(branch, SourceRevision):
        return {
            "repo_id": branch.repo_id,
            "source_id": branch.source_id,
            "source_type": branch.source_type,
            "revision_key": branch.revision_key,
            "revision_label": branch.revision_label,
            "content_identity": branch.content_identity,
            "branch_key": branch.branch_key or branch.revision_key,
            "branch_name": branch.branch_name or branch.revision_label,
            "commit_sha": branch.commit_sha,
            "dirty": int(branch.dirty),
        }
    return {
        "repo_id": branch.repo_id,
        "source_id": branch.repo_id,
        "source_type": "git",
        "revision_key": branch.branch_key,
        "revision_label": branch.branch_name,
        "content_identity": branch.commit_sha or branch.branch_key,
        "branch_key": branch.branch_key,
        "branch_name": branch.branch_name,
        "commit_sha": branch.commit_sha,
        "dirty": int(branch.dirty),
    }


def file_record(path: Path, project_id: str, branch_key: str, rel_path: str) -> dict[str, Any] | None:
    init_db(path)
    with closing(_connect(path)) as conn:
        row = conn.execute(
            "SELECT * FROM code_files WHERE project_id=? AND branch_key=? AND path=?",
            (project_id, branch_key, rel_path),
        ).fetchone()
        return dict(row) if row else None


def replace_file(
    path: Path,
    *,
    file_id: str,
    project_id: str,
    branch: BranchIdentity | SourceRevision,
    rel_path: str,
    content_hash: str,
    size_bytes: int,
    parsed: ParsedFile,
    indexed_at: str,
) -> dict[str, int]:
    # Parser identifiers describe local syntax occurrences. Re-key them with
    # the branch-specific file occurrence before persistence. Without this,
    # identical code on two branches would collide on the SQLite primary keys
    # even though the content-addressed embedding itself is intentionally
    # reusable across those branches.
    symbol_ids = {
        symbol.symbol_id: hashlib.sha256(
            f"{file_id}|symbol|{symbol.symbol_id}".encode("utf-8")
        ).hexdigest()
        for symbol in parsed.symbols
    }
    references, duplicate_reference_count = _deduplicate_references(parsed.references)
    diagnostics = list(parsed.diagnostics)
    if duplicate_reference_count:
        diagnostics.append(
            f"storage: deduplicated {duplicate_reference_count} identical parser reference emission(s)"
        )

    rev = _revision_fields(branch)
    init_db(path)
    with closing(_connect(path)) as conn:
        with conn:
            old = conn.execute(
                "SELECT file_id FROM code_files WHERE project_id=? AND source_id=? AND revision_key=? AND path=?",
                (project_id, rev["source_id"], rev["revision_key"], rel_path),
            ).fetchone()
            if old:
                old_id = str(old["file_id"])
                conn.execute("DELETE FROM code_chunks_fts WHERE chunk_id IN (SELECT chunk_id FROM code_chunks WHERE file_id=?)", (old_id,))
                conn.execute("DELETE FROM code_files WHERE file_id=?", (old_id,))
            conn.execute(
                """
                INSERT INTO code_files(
                    file_id, project_id, repo_id, source_id, source_type, revision_key,
                    revision_label, content_identity, branch_key, branch_name, commit_sha, dirty,
                    path, language, content_hash, size_bytes, parser_id, parse_mode,
                    parse_status, diagnostics_json, indexed_at
                ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                (
                    file_id, project_id, rev["repo_id"], rev["source_id"], rev["source_type"],
                    rev["revision_key"], rev["revision_label"], rev["content_identity"],
                    rev["branch_key"], rev["branch_name"], rev["commit_sha"], rev["dirty"],
                    rel_path, parsed.language, content_hash, size_bytes, parsed.parser_id,
                    parsed.parse_mode, parsed.parse_status, json.dumps(diagnostics, ensure_ascii=False), indexed_at,
                ),
            )
            for symbol in parsed.symbols:
                occurrence_symbol_id = symbol_ids[symbol.symbol_id]
                conn.execute(
                    """
                    INSERT INTO code_symbols(
                        symbol_id, file_id, name, qualified_name, kind, parent_symbol_id,
                        start_byte, end_byte, start_line, end_line, signature, content_hash
                    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
                    """,
                    (
                        occurrence_symbol_id, file_id, symbol.name, symbol.qualified_name, symbol.kind,
                        symbol_ids.get(symbol.parent_symbol_id or ""), symbol.start_byte, symbol.end_byte,
                        symbol.start_line, symbol.end_line, symbol.signature, symbol.content_hash,
                    ),
                )
            signatures = {symbol_ids[symbol.symbol_id]: symbol.signature for symbol in parsed.symbols}
            for chunk in parsed.chunks:
                occurrence_symbol_id = symbol_ids.get(chunk.symbol_id or "")
                occurrence_chunk_id = hashlib.sha256(
                    f"{file_id}|chunk|{chunk.chunk_id}".encode("utf-8")
                ).hexdigest()
                conn.execute(
                    """
                    INSERT INTO code_chunks(
                        chunk_id, file_id, symbol_id, symbol_name, qualified_name, symbol_kind,
                        chunk_part, chunk_total, start_line, end_line, title, text,
                        content_hash, embedding_key
                    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                    """,
                    (
                        occurrence_chunk_id, file_id, occurrence_symbol_id, chunk.symbol_name,
                        chunk.qualified_name, chunk.symbol_kind, chunk.chunk_part,
                        chunk.chunk_total, chunk.start_line, chunk.end_line, chunk.title,
                        chunk.text, chunk.content_hash, chunk.embedding_key,
                    ),
                )
                conn.execute(
                    """
                    INSERT INTO code_chunks_fts(
                        chunk_id, project_id, repo_id, source_id, source_type, revision_key, branch_key, path, language,
                        symbol_name, qualified_name, signature, text
                    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
                    """,
                    (
                        occurrence_chunk_id, project_id, rev["repo_id"], rev["source_id"], rev["source_type"],
                        rev["revision_key"], rev["branch_key"], rel_path, parsed.language,
                        chunk.symbol_name, chunk.qualified_name, signatures.get(occurrence_symbol_id or "", ""), chunk.text,
                    ),
                )
            for reference in references:
                occurrence_reference_id = hashlib.sha256(
                    f"{file_id}|reference|{reference.reference_id}".encode("utf-8")
                ).hexdigest()
                conn.execute(
                    """
                    INSERT INTO code_references(
                        reference_id, file_id, source_symbol_id, reference_kind, target_name,
                        target_qualified_hint, line, column_no, source_text, control_context_json
                    ) VALUES(?,?,?,?,?,?,?,?,?,?)
                    """,
                    (
                        occurrence_reference_id, file_id,
                        symbol_ids.get(reference.source_symbol_id or ""),
                        reference.reference_kind, reference.target_name,
                        reference.target_qualified_hint, reference.line, reference.column,
                        reference.source_text,
                        json.dumps(list(reference.control_context), ensure_ascii=False),
                    ),
                )
    return {
        "references_input": len(parsed.references),
        "references_stored": len(references),
        "duplicate_references_deduplicated": duplicate_reference_count,
    }


def update_branch_metadata(path: Path, project_id: str, branch: BranchIdentity | SourceRevision, indexed_at: str) -> int:
    """Refresh occurrence metadata without reparsing unchanged source.

    A commit can advance while a file's bytes remain unchanged. The structural
    content and vector are reusable, but every returned hit and Qdrant
    membership must still identify the currently inspected commit/worktree.
    """
    rev = _revision_fields(branch)
    init_db(path)
    with closing(_connect(path)) as conn, conn:
        cursor = conn.execute(
            """
            UPDATE code_files
            SET source_type=?, revision_label=?, content_identity=?, branch_name=?, commit_sha=?, dirty=?, indexed_at=?
            WHERE project_id=? AND source_id=? AND revision_key=? AND (
                source_type<>? OR revision_label<>? OR content_identity<>? OR branch_name<>? OR commit_sha<>? OR dirty<>?
            )
            """,
            (
                rev["source_type"], rev["revision_label"], rev["content_identity"], rev["branch_name"], rev["commit_sha"], rev["dirty"], indexed_at,
                project_id, rev["source_id"], rev["revision_key"],
                rev["source_type"], rev["revision_label"], rev["content_identity"], rev["branch_name"], rev["commit_sha"], rev["dirty"],
            ),
        )
        return int(cursor.rowcount or 0)


def delete_stale_files(path: Path, project_id: str, branch_key: str, current_paths: set[str]) -> list[str]:
    init_db(path)
    removed: list[str] = []
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            "SELECT file_id, path FROM code_files WHERE project_id=? AND branch_key=?",
            (project_id, branch_key),
        ).fetchall()
        with conn:
            for row in rows:
                rel = str(row["path"])
                if rel in current_paths:
                    continue
                file_id = str(row["file_id"])
                conn.execute("DELETE FROM code_chunks_fts WHERE chunk_id IN (SELECT chunk_id FROM code_chunks WHERE file_id=?)", (file_id,))
                conn.execute("DELETE FROM code_files WHERE file_id=?", (file_id,))
                removed.append(rel)
    return removed


def branch_embedding_memberships(path: Path, project_id: str, branch_key: str) -> list[dict[str, Any]]:
    init_db(path)
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT c.embedding_key, c.chunk_id, c.content_hash, c.text, c.start_line, c.end_line,
                   c.symbol_id, c.symbol_name, c.qualified_name, c.symbol_kind,
                   f.repo_id, f.source_id, f.source_type, f.revision_key, f.content_identity,
                   f.path, f.language, f.commit_sha, f.dirty
            FROM code_chunks c JOIN code_files f ON f.file_id=c.file_id
            WHERE f.project_id=? AND f.branch_key=?
            ORDER BY c.embedding_key, f.path, c.start_line, c.chunk_id
            """,
            (project_id, branch_key),
        ).fetchall()
        return [dict(row) for row in rows]


def synced_vector_memberships(path: Path, project_id: str, branch_key: str) -> list[dict[str, Any]]:
    """Return the last branch membership set confirmed written to Qdrant.

    This is deliberately separate from the current SQLite code index. If a
    source update succeeds locally but the remote vector update fails, the
    previous snapshot is retained so the next retry can still remove stale
    remote memberships rather than forgetting what Qdrant may contain.
    """
    init_db(path)
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT embedding_key, chunk_id, content_hash, text, repo_id, source_id, source_type,
                   revision_key, content_identity, path, symbol_id, symbol_name, qualified_name, symbol_kind, language,
                   start_line, end_line, commit_sha, dirty
            FROM code_vector_memberships
            WHERE project_id=? AND branch_key=?
            ORDER BY embedding_key, path, start_line, chunk_id
            """,
            (project_id, branch_key),
        ).fetchall()
        return [dict(row) for row in rows]


def replace_synced_vector_memberships(
    path: Path,
    project_id: str,
    branch_key: str,
    rows: list[dict[str, Any]],
) -> None:
    """Atomically record the membership set confirmed written to Qdrant."""
    init_db(path)
    with closing(_connect(path)) as conn, conn:
        conn.execute(
            "DELETE FROM code_vector_memberships WHERE project_id=? AND branch_key=?",
            (project_id, branch_key),
        )
        conn.executemany(
            """
            INSERT INTO code_vector_memberships(
                project_id, branch_key, embedding_key, chunk_id, content_hash,
                text, repo_id, source_id, source_type, revision_key, content_identity, path,
                symbol_id, symbol_name, qualified_name, symbol_kind, language, start_line, end_line, commit_sha, dirty
            ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """,
            [
                (
                    project_id,
                    branch_key,
                    str(row.get("embedding_key") or ""),
                    str(row.get("chunk_id") or ""),
                    str(row.get("content_hash") or ""),
                    str(row.get("text") or ""),
                    str(row.get("repo_id") or ""),
                    str(row.get("source_id") or row.get("repo_id") or ""),
                    str(row.get("source_type") or "git"),
                    str(row.get("revision_key") or branch_key),
                    str(row.get("content_identity") or row.get("commit_sha") or branch_key),
                    str(row.get("path") or ""),
                    str(row.get("symbol_id") or ""),
                    str(row.get("symbol_name") or ""),
                    str(row.get("qualified_name") or ""),
                    str(row.get("symbol_kind") or ""),
                    str(row.get("language") or ""),
                    int(row.get("start_line") or 1),
                    int(row.get("end_line") or row.get("start_line") or 1),
                    str(row.get("commit_sha") or ""),
                    int(bool(row.get("dirty"))),
                )
                for row in rows
            ],
        )


def _edge_id(reference_id: str, target: str) -> str:
    import hashlib
    return hashlib.sha256(f"{reference_id}|{target}".encode()).hexdigest()


def _decode_context(value: Any) -> list[str]:
    try:
        parsed = json.loads(str(value or "[]"))
    except json.JSONDecodeError:
        return []
    return [str(item) for item in parsed] if isinstance(parsed, list) else []


def _qualified_candidates(
    conn: sqlite3.Connection,
    *,
    branch_key: str,
    suffix: str,
) -> list[sqlite3.Row]:
    normalized = suffix.strip(".")
    if not normalized:
        return []
    if "->" in normalized:
        return conn.execute(
            """
            SELECT s.symbol_id FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
            WHERE f.branch_key=? AND s.qualified_name=? COLLATE BINARY
            ORDER BY f.path, s.start_line
            """,
            (branch_key, normalized),
        ).fetchall()
    return conn.execute(
        """
        SELECT s.symbol_id FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
        WHERE f.branch_key=? AND (
            s.qualified_name = ? COLLATE BINARY OR
            substr(s.qualified_name, -(length(?) + 1)) = ('.' || ?) COLLATE BINARY
        )
        ORDER BY f.path, s.start_line
        """,
        (branch_key, normalized, normalized, normalized),
    ).fetchall()


def _merge_import_qualification(imported_hint: str, tail: str) -> str:
    """Join an imported module/symbol with a qualified call without duplication."""
    base = [part for part in imported_hint.strip(".").split(".") if part]
    suffix = [part for part in tail.strip(".").split(".") if part]
    overlap = 0
    for size in range(min(len(base), len(suffix)), 0, -1):
        if base[-size:] == suffix[:size]:
            overlap = size
            break
    return ".".join(base + suffix[overlap:])


def resolve_call_graph(path: Path, branch_key: str) -> dict[str, int]:
    """Resolve only static call edges whose target can be selected uniquely."""
    init_db(path)
    resolved = ambiguous = unresolved = 0
    with closing(_connect(path)) as conn:
        refs = conn.execute(
            """
            SELECT r.*, f.path AS source_path, s.parent_symbol_id AS source_parent_symbol_id
            FROM code_references r
            JOIN code_files f ON f.file_id=r.file_id
            JOIN code_symbols s ON s.symbol_id=r.source_symbol_id
            WHERE f.branch_key=? AND r.reference_kind='call' AND r.source_symbol_id IS NOT NULL
            """,
            (branch_key,),
        ).fetchall()
        with conn:
            conn.execute("DELETE FROM code_edges WHERE branch_key=?", (branch_key,))
            for ref in refs:
                target_name = str(ref["target_name"])
                qualified_hint = str(ref["target_qualified_hint"] or "").strip()
                candidates: list[sqlite3.Row] = []
                method = "unresolved"
                confidence = "low"

                # Smali and other deterministic textual IRs can encode an exact
                # declaring type + method descriptor in the call itself. Resolve
                # that identity directly rather than degrading it to a name-only
                # guess.
                if qualified_hint and "->" in qualified_hint:
                    candidates = _qualified_candidates(conn, branch_key=branch_key, suffix=qualified_hint)
                    method = "qualified_exact"
                    confidence = "high" if len(candidates) == 1 else "low"

                # self.foo()/this.foo() resolves first within the containing class.
                if ref["source_parent_symbol_id"] and qualified_hint.startswith(("self.", "this.")):
                    candidates = conn.execute(
                        """
                        SELECT s.symbol_id FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
                        WHERE f.branch_key=? AND f.path=? AND s.parent_symbol_id=? AND s.name=?
                        ORDER BY s.start_line
                        """,
                        (branch_key, ref["source_path"], ref["source_parent_symbol_id"], target_name),
                    ).fetchall()
                    method = "same_type_member"
                    confidence = "medium"

                # A unique same-file definition is deterministic only for an
                # unqualified call. Resolving obj.foo() merely because foo is
                # unique would be unsound without receiver type information.
                if not candidates and (not qualified_hint or "." not in qualified_hint):
                    candidates = conn.execute(
                        """
                        SELECT s.symbol_id FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
                        WHERE f.branch_key=? AND f.path=? AND s.name=?
                        ORDER BY (s.parent_symbol_id IS NULL) DESC, s.start_line
                        """,
                        (branch_key, ref["source_path"], target_name),
                    ).fetchall()
                    method = "same_file_exact"
                    confidence = "medium"

                # Qualified receiver calls are resolved only through an explicit
                # import binding. A textual receiver such as service.run() may
                # be a local variable, dynamically injected object, or class; a
                # matching qualified symbol name alone is not enough evidence.
                if len(candidates) != 1:
                    root_name = qualified_hint.split(".", 1)[0] if qualified_hint else target_name
                    imports = conn.execute(
                        """
                        SELECT target_name, target_qualified_hint
                        FROM code_references
                        WHERE file_id=? AND reference_kind='import' AND target_name=?
                        """,
                        (ref["file_id"], root_name),
                    ).fetchall()
                    imported_candidates: dict[str, sqlite3.Row] = {}
                    for imported in imports:
                        imported_hint = str(imported["target_qualified_hint"] or "")
                        if qualified_hint and "." in qualified_hint:
                            tail = qualified_hint.split(".", 1)[1]
                            imported_hint = _merge_import_qualification(imported_hint, tail)
                        for candidate in _qualified_candidates(conn, branch_key=branch_key, suffix=imported_hint):
                            imported_candidates[str(candidate["symbol_id"])] = candidate
                    if imported_candidates:
                        candidates = list(imported_candidates.values())
                        method = "import_qualified"
                        confidence = "medium" if len(candidates) == 1 else "low"

                if len(candidates) != 1 and (not qualified_hint or "." not in qualified_hint):
                    candidates = conn.execute(
                        """
                        SELECT s.symbol_id FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
                        WHERE f.branch_key=? AND s.name=?
                        ORDER BY f.path, s.start_line
                        """,
                        (branch_key, target_name),
                    ).fetchall()
                    method = "unique_branch_name"
                    confidence = "low"

                count = len(candidates)
                if count == 1:
                    target_id = str(candidates[0]["symbol_id"])
                    status = "resolved"
                    resolved += 1
                elif count > 1:
                    target_id = None
                    status = "ambiguous"
                    ambiguous += 1
                else:
                    target_id = None
                    status = "unresolved"
                    unresolved += 1
                conn.execute(
                    """
                    INSERT INTO code_edges(
                        edge_id, branch_key, source_symbol_id, target_symbol_id, target_name,
                        edge_kind, line, confidence, resolution_status, resolution_method,
                        candidate_count, source_text, control_context_json
                    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
                    """,
                    (
                        _edge_id(str(ref["reference_id"]), target_id or target_name),
                        branch_key, ref["source_symbol_id"], target_id, target_name, "call",
                        ref["line"], confidence, status, method, count,
                        str(ref["source_text"] or ""), str(ref["control_context_json"] or "[]"),
                    ),
                )
    return {"resolved": resolved, "ambiguous": ambiguous, "unresolved": unresolved}


def write_state(
    path: Path,
    *,
    branch: BranchIdentity | SourceRevision,
    project_id: str,
    source_probe_hash: str,
    parser_profile_hash: str,
    embedding_profile_hash: str,
    document_set_hash: str,
    qdrant_membership_hash: str,
    indexed_at: str,
    vector_status: str,
    vector_reason: str,
    engine_version: str,
) -> None:
    rev = _revision_fields(branch)
    init_db(path)
    with closing(_connect(path)) as conn, conn:
        conn.execute(
            """
            INSERT INTO code_index_state(
                branch_key, schema_version, engine_version, project_id, repo_id, source_id, source_type,
                revision_key, revision_label, content_identity, branch_name, commit_sha, dirty, source_probe_hash, parser_profile_hash,
                embedding_profile_hash, document_set_hash, qdrant_membership_hash, indexed_at, vector_status, vector_reason
            ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(branch_key) DO UPDATE SET
                schema_version=excluded.schema_version,
                engine_version=excluded.engine_version,
                project_id=excluded.project_id,
                repo_id=excluded.repo_id,
                source_id=excluded.source_id,
                source_type=excluded.source_type,
                revision_key=excluded.revision_key,
                revision_label=excluded.revision_label,
                content_identity=excluded.content_identity,
                branch_name=excluded.branch_name,
                commit_sha=excluded.commit_sha,
                dirty=excluded.dirty,
                source_probe_hash=excluded.source_probe_hash,
                parser_profile_hash=excluded.parser_profile_hash,
                embedding_profile_hash=excluded.embedding_profile_hash,
                document_set_hash=excluded.document_set_hash,
                qdrant_membership_hash=excluded.qdrant_membership_hash,
                indexed_at=excluded.indexed_at,
                vector_status=excluded.vector_status,
                vector_reason=excluded.vector_reason
            """,
            (
                rev["branch_key"], SCHEMA_VERSION, engine_version, project_id, rev["repo_id"],
                rev["source_id"], rev["source_type"], rev["revision_key"], rev["revision_label"],
                rev["content_identity"], rev["branch_name"], rev["commit_sha"], rev["dirty"],
                source_probe_hash, parser_profile_hash, embedding_profile_hash, document_set_hash,
                qdrant_membership_hash, indexed_at, vector_status, vector_reason,
            ),
        )


def read_state(path: Path, branch_key: str) -> dict[str, Any]:
    init_db(path)
    with closing(_connect(path)) as conn:
        row = conn.execute("SELECT * FROM code_index_state WHERE branch_key=?", (branch_key,)).fetchone()
        return dict(row) if row else {}


def state_for_source(path: Path, project_id: str, source_id: str) -> dict[str, Any]:
    """Return the most recently materialized revision for a registered source.

    This is intentionally a SQLite-only lookup so passive status can report a
    non-Git corpus without hashing the entire source tree. Deep verification or
    interactive search recomputes the content-manifest identity separately.
    """
    init_db(path)
    with closing(_connect(path)) as conn:
        row = conn.execute(
            """
            SELECT * FROM code_index_state
            WHERE project_id=? AND source_id=?
            ORDER BY indexed_at DESC LIMIT 1
            """,
            (project_id, source_id),
        ).fetchone()
        return dict(row) if row else {}


def counts(path: Path, branch_key: str) -> dict[str, int]:
    init_db(path)
    with closing(_connect(path)) as conn:
        out: dict[str, int] = {}
        queries = {
            "files": "SELECT COUNT(*) FROM code_files WHERE branch_key=?",
            "symbols": "SELECT COUNT(*) FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id WHERE f.branch_key=?",
            "chunks": "SELECT COUNT(*) FROM code_chunks c JOIN code_files f ON f.file_id=c.file_id WHERE f.branch_key=?",
            "references": "SELECT COUNT(*) FROM code_references r JOIN code_files f ON f.file_id=r.file_id WHERE f.branch_key=?",
            "edges": "SELECT COUNT(*) FROM code_edges WHERE branch_key=?",
            "fallback_files": "SELECT COUNT(*) FROM code_files WHERE branch_key=? AND parse_mode!='tree_sitter'",
        }
        for key, sql in queries.items():
            out[key] = int(conn.execute(sql, (branch_key,)).fetchone()[0])
        return out


_FTS_STOP_TERMS = {
    "a", "an", "and", "are", "as", "at", "be", "been", "before", "by", "can",
    "code", "does", "find", "for", "from", "how", "in", "into", "is", "it", "its",
    "of", "on", "or", "show", "that", "the", "their", "then", "this", "to", "where",
    "which", "with", "would", "could", "should", "when", "what", "who", "why",
}


def identifier_lexemes(value: str) -> list[str]:
    """Return deterministic language-neutral lexical forms for code identifiers.

    The structural parsers intentionally preserve each language's native symbol
    spelling. Lexical retrieval still needs common source conventions to compare
    naturally: ``bearer-token``, ``bearer_token``, ``BearerToken``,
    ``getHTTPResponse``, Java/Swift dotted members, Go receiver notation, Smali
    arrows, paths, and similar spellings should contribute compatible terms.

    This helper is deliberately syntax-agnostic. It does not stem or guess a
    programming language; it only decomposes punctuation and ASCII case
    boundaries while preserving compact forms. Adjacent recombinations retain
    useful forms such as ``OAuth2`` and ``URLSession`` that naive camel-case
    splitting can otherwise damage.
    """
    text = str(value or "").strip()
    if not text:
        return []

    coarse: list[str] = []
    current: list[str] = []
    for char in text:
        if char.isalnum():
            current.append(char)
        elif current:
            coarse.append("".join(current))
            current = []
    if current:
        coarse.append("".join(current))

    output: list[str] = []
    seen: set[str] = set()

    def add(term: str) -> None:
        normalized = term.casefold().strip()
        if len(normalized) < 2 or normalized in seen:
            return
        seen.add(normalized)
        output.append(normalized)

    for segment in coarse:
        add(segment)
        # Standard language-neutral boundaries: lower/digit -> upper and
        # acronym -> TitleCase (HTTPResponse -> HTTP + Response).
        split = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", segment)
        split = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", split)
        parts = [part for part in split.split() if part]
        for part in parts:
            add(part)
        # Recombine adjacent pieces as aliases. This recovers mixed-brand and
        # acronym forms such as O + Auth2 -> oauth2 and URL + Session ->
        # urlsession without language- or framework-specific dictionaries.
        for width in (2, 3):
            for index in range(0, max(0, len(parts) - width + 1)):
                add("".join(parts[index:index + width]))

    return output


def _raw_fts_terms(query: str) -> list[str]:
    # Keep common source punctuation in the original token so exact spellings
    # remain useful; identifier_lexemes() contributes separator/case aliases.
    # str.isalnum() deliberately preserves non-ASCII identifier text supported
    # by SQLite unicode61 instead of restricting lexical retrieval to English.
    allowed_punctuation = {"_", "$", "@", "#", ".", "/", ":", "-"}
    terms: list[str] = []
    current: list[str] = []
    for char in str(query or ""):
        if char.isalnum() or char in allowed_punctuation:
            current.append(char)
            continue
        if len(current) >= 2:
            terms.append("".join(current))
        current = []
    if len(current) >= 2:
        terms.append("".join(current))
    return terms


def _fts_query_terms(query: str, *, limit: int = 24) -> list[str]:
    raw_terms = _raw_fts_terms(query)
    terms: list[str] = []
    seen: set[str] = set()

    def add(term: str) -> None:
        normalized = str(term or "").casefold().strip()
        if len(normalized) < 2 or normalized in _FTS_STOP_TERMS or normalized in seen:
            return
        seen.add(normalized)
        terms.append(str(term))

    for raw in raw_terms:
        add(raw)
        for alias in identifier_lexemes(raw):
            add(alias)
        if len(terms) >= limit:
            break

    # Preserve the historical all-stop-word behavior instead of turning a
    # lexical request into an empty query.
    if not terms:
        for raw in raw_terms:
            normalized = raw.casefold()
            if normalized not in seen:
                seen.add(normalized)
                terms.append(raw)
            if len(terms) >= limit:
                break
    return terms[:limit]


def _fts_query(query: str) -> str:
    terms = _fts_query_terms(query)
    return " OR ".join(f'"{term.replace(chr(34), chr(34) * 2)}"' for term in terms)


def _identifier_bridge_terms(query: str, *, limit: int = 12) -> list[str]:
    """Specific atoms used to bridge tokenizer/case conventions.

    These are substring predicates over bounded structural metadata and text,
    not semantic expansion or stemming. Long/specific terms are considered
    first so generic role words cannot dominate the bridge.
    """
    ordered: list[str] = []
    seen: set[str] = set()
    for raw in _raw_fts_terms(query):
        candidates = identifier_lexemes(raw) or [raw.casefold()]
        for term in candidates:
            normalized = term.casefold()
            if len(normalized) < 3 or normalized in _FTS_STOP_TERMS or normalized in seen:
                continue
            seen.add(normalized)
            ordered.append(normalized)
    ordered.sort(key=lambda value: (-len(value), value))
    return ordered[:limit]


def _identifier_bridge_rows(
    conn: sqlite3.Connection,
    project_id: str,
    branch_key: str,
    query: str,
    limit: int,
) -> list[dict[str, Any]]:
    """Bounded lexical bridge for separator/case-tokenizer mismatches.

    FTS5 cannot match a suffix inside one camelCase token (``bearer`` inside
    ``validateBearerToken``), and Awoki intentionally keeps punctuation such as
    ``-`` tokenized for paths/API names. This secondary local lexical pass only
    compares literal query atoms against already-indexed path/symbol/signature
    metadata and chunk text. It is language-neutral and network-free.
    """
    terms = _identifier_bridge_terms(query)
    if not terms:
        return []

    coverage_parts: list[str] = []
    weighted_parts: list[str] = []
    where_parts: list[str] = []
    coverage_params: list[Any] = []
    weighted_params: list[Any] = []
    where_params: list[Any] = []

    for term in terms:
        # Each atom counts once for coverage when it occurs in any indexed
        # representation. Structural identity fields carry higher weight than
        # source text, which keeps ordinary prose/code-body coincidences weak.
        predicate = (
            "instr(lower(f.path), ?) > 0 OR "
            "instr(lower(c.symbol_name), ?) > 0 OR "
            "instr(lower(c.qualified_name), ?) > 0 OR "
            "instr(lower(COALESCE(s.signature,'')), ?) > 0 OR "
            "instr(lower(c.text), ?) > 0"
        )
        coverage_parts.append(f"CASE WHEN ({predicate}) THEN 1 ELSE 0 END")
        coverage_params.extend([term] * 5)

        weighted_parts.append(
            "(CASE WHEN instr(lower(c.symbol_name), ?) > 0 THEN 8 ELSE 0 END + "
            " CASE WHEN instr(lower(c.qualified_name), ?) > 0 THEN 6 ELSE 0 END + "
            " CASE WHEN instr(lower(f.path), ?) > 0 THEN 5 ELSE 0 END + "
            " CASE WHEN instr(lower(COALESCE(s.signature,'')), ?) > 0 THEN 3 ELSE 0 END + "
            " CASE WHEN instr(lower(c.text), ?) > 0 THEN 1 ELSE 0 END)"
        )
        weighted_params.extend([term] * 5)
        where_parts.append(f"({predicate})")
        where_params.extend([term] * 5)

    coverage_sql = " + ".join(coverage_parts) or "0"
    weighted_sql = " + ".join(weighted_parts) or "0"
    where_sql = " OR ".join(where_parts) or "0"
    params = coverage_params + weighted_params + where_params + [
        project_id, branch_key, max(1, min(int(limit), 200))
    ]

    sql = f"""
        SELECT c.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key,
               f.revision_label, f.content_identity, f.branch_key, f.branch_name,
               f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
               f.parse_mode, f.parse_status, f.diagnostics_json, s.signature,
               ({coverage_sql}) AS lexical_coverage,
               ({weighted_sql}) AS lexical_weight
        FROM code_chunks c
        JOIN code_files f ON f.file_id=c.file_id
        LEFT JOIN code_symbols s ON s.symbol_id=c.symbol_id
        WHERE ({where_sql}) AND f.project_id=? AND f.branch_key=?
        ORDER BY lexical_coverage DESC, lexical_weight DESC, f.path, c.start_line, c.chunk_id
        LIMIT ?
    """
    rows = conn.execute(sql, params).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        item = dict(row)
        haystacks = [
            str(item.get("path") or "").casefold(),
            str(item.get("symbol_name") or "").casefold(),
            str(item.get("qualified_name") or "").casefold(),
            str(item.get("signature") or "").casefold(),
            str(item.get("text") or "").casefold(),
        ]
        item["lexical_normalization_terms"] = [
            term for term in terms if any(term in value for value in haystacks)
        ]
        item["lexical_match_mode"] = "identifier_bridge"
        out.append(item)
    return out


def search_fts(path: Path, project_id: str, branch_key: str, query: str, limit: int) -> list[dict[str, Any]]:
    init_db(path)
    expression = _fts_query(query)
    if not expression:
        return []
    bounded_limit = max(1, min(int(limit), 200))
    with closing(_connect(path)) as conn:
        try:
            direct_rows = conn.execute(
                """
                SELECT fts.chunk_id, bm25(code_chunks_fts, 0.0, 0.0, 0.0, 0.0, 1.8, 1.2, 2.5, 3.0, 2.0, 1.0) AS rank,
                       c.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                       f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                       f.parse_mode, f.parse_status, f.diagnostics_json, s.signature
                FROM code_chunks_fts fts
                JOIN code_chunks c ON c.chunk_id=fts.chunk_id
                JOIN code_files f ON f.file_id=c.file_id
                LEFT JOIN code_symbols s ON s.symbol_id=c.symbol_id
                WHERE code_chunks_fts MATCH ? AND f.project_id=? AND f.branch_key=?
                ORDER BY rank LIMIT ?
                """,
                (expression, project_id, branch_key, bounded_limit),
            ).fetchall()
        except sqlite3.OperationalError:
            direct_rows = []
        try:
            bridge_rows = _identifier_bridge_rows(conn, project_id, branch_key, query, bounded_limit)
        except sqlite3.OperationalError:
            # The bridge is supplemental. A malformed/unsupported local SQLite
            # expression must never erase otherwise-valid native FTS results.
            bridge_rows = []

        # Fuse the native FTS5 order and identifier-normalization bridge locally.
        # This preserves BM25 as the primary lexical signal while giving strong
        # separator/camel-case matches a bounded independent lexical opportunity.
        merged: dict[str, dict[str, Any]] = {}
        k = 40.0
        for rank, row in enumerate(direct_rows, start=1):
            item = dict(row)
            item["fts_raw_score"] = 1.0 / (1.0 + abs(float(item.pop("rank") or 0.0)))
            item["lexical_match_mode"] = "sqlite_fts"
            item["lexical_normalization_terms"] = []
            item["_lexical_rrf"] = 1.0 / (k + rank)
            merged[str(item["chunk_id"])] = item

        for rank, row in enumerate(bridge_rows, start=1):
            item = dict(row)
            key = str(item["chunk_id"])
            contribution = 0.75 / (k + rank)
            existing = merged.get(key)
            if existing is None:
                item["fts_raw_score"] = 0.0
                item["_lexical_rrf"] = contribution
                merged[key] = item
            else:
                existing["_lexical_rrf"] = float(existing.get("_lexical_rrf") or 0.0) + contribution
                existing["lexical_match_mode"] = "sqlite_fts+identifier_bridge"
                existing["lexical_normalization_terms"] = list(item.get("lexical_normalization_terms") or [])
                existing["lexical_coverage"] = item.get("lexical_coverage")
                existing["lexical_weight"] = item.get("lexical_weight")

        ranked = sorted(
            merged.values(),
            key=lambda item: (
                -float(item.get("_lexical_rrf") or 0.0),
                str(item.get("path") or ""),
                int(item.get("start_line") or 0),
                str(item.get("chunk_id") or ""),
            ),
        )[:bounded_limit]
        out: list[dict[str, Any]] = []
        for item in ranked:
            item = dict(item)
            item["score"] = float(item.pop("_lexical_rrf") or 0.0)
            item["retrieval_backend"] = "code_fts"
            out.append(item)
        return out


def _literal_like_pattern(value: str) -> str:
    # LIKE is useful for bounded source/path substring lookup, but `%` and `_`
    # must remain literal in an operation named exact search.
    escaped = value.replace("!", "!!").replace("%", "!%").replace("_", "!_")
    return f"%{escaped}%"


def exact_search(path: Path, project_id: str, branch_key: str, query: str, limit: int) -> list[dict[str, Any]]:
    init_db(path)
    pattern = _literal_like_pattern(query)
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT c.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json, s.signature
            FROM code_chunks c JOIN code_files f ON f.file_id=c.file_id
            LEFT JOIN code_symbols s ON s.symbol_id=c.symbol_id
            WHERE f.project_id=? AND f.branch_key=? AND (
                c.symbol_name=? OR c.qualified_name=? OR c.text LIKE ? ESCAPE '!' OR f.path LIKE ? ESCAPE '!'
            )
            ORDER BY
                (c.qualified_name=?) DESC,
                (c.symbol_name=?) DESC,
                (f.path LIKE ? ESCAPE '!') DESC,
                f.path, c.start_line
            LIMIT ?
            """,
            (
                project_id, branch_key, query, query, pattern, pattern,
                query, query, pattern, max(1, min(limit, 200)),
            ),
        ).fetchall()
        out = []
        for index, row in enumerate(rows):
            item = dict(row)
            item["score"] = 4.0 if item["qualified_name"] == query else 3.0 if item["symbol_name"] == query else 1.0 / (index + 1)
            item["retrieval_backend"] = "exact_structural"
            out.append(item)
        return out


def definitions(path: Path, project_id: str, branch_key: str, symbol: str, limit: int = 20) -> list[dict[str, Any]]:
    init_db(path)
    normalized = symbol.strip().strip(".")
    if not normalized:
        return []
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT s.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json,
                   f.content_hash AS file_content_hash,
                   c.chunk_id, c.text, c.embedding_key, c.chunk_part, c.chunk_total,
                   CASE
                     WHEN s.qualified_name = ? COLLATE BINARY THEN 0
                     WHEN s.name = ? COLLATE BINARY THEN 1
                     WHEN lower(s.name) = lower(?) THEN 2
                     WHEN substr(s.qualified_name, -(length(?) + 1)) = ('.' || ?) COLLATE BINARY THEN 3
                     ELSE 9
                   END AS match_tier
            FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
            LEFT JOIN code_chunks c ON c.symbol_id=s.symbol_id AND c.chunk_part=1
            WHERE f.project_id=? AND f.branch_key=? AND (
                s.qualified_name = ? COLLATE BINARY OR
                s.name = ? COLLATE BINARY OR
                lower(s.name) = lower(?) OR
                substr(s.qualified_name, -(length(?) + 1)) = ('.' || ?) COLLATE BINARY
            )
            ORDER BY match_tier, f.path, s.start_line
            LIMIT ?
            """,
            (
                normalized, normalized, normalized, normalized, normalized,
                project_id, branch_key,
                normalized, normalized, normalized, normalized, normalized,
                max(1, min(max(limit, 20), 200)),
            ),
        ).fetchall()
        if rows:
            best_tier = int(rows[0]["match_tier"])
            rows = [row for row in rows if int(row["match_tier"]) == best_tier][: max(1, min(limit, 100))]
        out = []
        for index, row in enumerate(rows):
            item = dict(row)
            item["symbol_name"] = item["name"]
            item["symbol_kind"] = item["kind"]
            item["score"] = 5.0 - min(index, 4) * 0.25
            item["retrieval_backend"] = "definition_index"
            out.append(item)
        return out


def symbol_by_id(path: Path, symbol_id: str) -> dict[str, Any] | None:
    init_db(path)
    with closing(_connect(path)) as conn:
        row = conn.execute(
            """
            SELECT s.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json,
                   f.content_hash AS file_content_hash,
                   c.chunk_id, c.text, c.embedding_key, c.chunk_part, c.chunk_total
            FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
            LEFT JOIN code_chunks c ON c.symbol_id=s.symbol_id AND c.chunk_part=1
            WHERE s.symbol_id=?
            """,
            (symbol_id,),
        ).fetchone()
        if not row:
            return None
        item = dict(row)
        item["symbol_name"] = item["name"]
        item["symbol_kind"] = item["kind"]
        return item


def child_symbols(path: Path, parent_symbol_id: str, limit: int = 100) -> list[dict[str, Any]]:
    """Return direct structural children with their first searchable chunk.

    This intentionally stays a structural/index operation. It does not infer
    semantic relevance and it does not walk references/calls. Callers that want
    recursive refinement should bound that traversal explicitly.
    """
    init_db(path)
    if not parent_symbol_id:
        return []
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT s.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json,
                   f.content_hash AS file_content_hash,
                   c.chunk_id, c.text, c.embedding_key, c.chunk_part, c.chunk_total
            FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
            LEFT JOIN code_chunks c ON c.symbol_id=s.symbol_id AND c.chunk_part=1
            WHERE s.parent_symbol_id=?
            ORDER BY s.start_line, s.qualified_name
            LIMIT ?
            """,
            (parent_symbol_id, max(1, min(limit, 500))),
        ).fetchall()
        out: list[dict[str, Any]] = []
        for row in rows:
            item = dict(row)
            item["symbol_name"] = item["name"]
            item["symbol_kind"] = item["kind"]
            out.append(item)
        return out


def symbols_in_file(
    path: Path,
    project_id: str,
    branch_key: str,
    rel_path: str,
    *,
    kinds: set[str] | None = None,
    limit: int = 200,
) -> list[dict[str, Any]]:
    """Return indexed symbols from one source file with their first chunk.

    This is a structural fallback for coarse module/file refinement. Some
    language grammars (notably receiver-style methods) do not make every
    callable a direct syntactic child of the retrieved container. File-scoped
    enumeration is still deterministic because it is constrained to the exact
    indexed file/branch and never infers semantic relevance.
    """
    init_db(path)
    normalized_kinds = {str(kind).lower() for kind in (kinds or set()) if str(kind)}
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT s.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json,
                   f.content_hash AS file_content_hash,
                   c.chunk_id, c.text, c.embedding_key, c.chunk_part, c.chunk_total
            FROM code_symbols s JOIN code_files f ON f.file_id=s.file_id
            LEFT JOIN code_chunks c ON c.symbol_id=s.symbol_id AND c.chunk_part=1
            WHERE f.project_id=? AND f.branch_key=? AND f.path=?
            ORDER BY s.start_line, s.qualified_name
            LIMIT ?
            """,
            (project_id, branch_key, rel_path, max(1, min(limit, 1000))),
        ).fetchall()
        out: list[dict[str, Any]] = []
        for row in rows:
            item = dict(row)
            item["symbol_name"] = item["name"]
            item["symbol_kind"] = item["kind"]
            if normalized_kinds and str(item.get("symbol_kind") or "").lower() not in normalized_kinds:
                continue
            out.append(item)
        return out


def callers(path: Path, branch_key: str, symbol_id: str, target_name: str) -> list[dict[str, Any]]:
    init_db(path)
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT e.*, s.symbol_id AS symbol_id, s.name, s.qualified_name, s.kind, s.signature,
                   f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name, f.commit_sha,
                   f.dirty, f.path, f.language, f.parser_id, f.parse_mode,
                   f.parse_status, f.diagnostics_json, s.start_line, s.end_line,
                   c.chunk_id, c.text, c.embedding_key
            FROM code_edges e
            JOIN code_symbols s ON s.symbol_id=e.source_symbol_id
            JOIN code_files f ON f.file_id=s.file_id
            LEFT JOIN code_chunks c ON c.symbol_id=s.symbol_id AND c.chunk_part=1
            WHERE e.branch_key=? AND (
                e.target_symbol_id=? OR (e.target_symbol_id IS NULL AND e.target_name=?)
            )
            ORDER BY (e.resolution_status='resolved') DESC, f.path, e.line
            """,
            (branch_key, symbol_id, target_name),
        ).fetchall()
        return [_graph_row(row, "call_graph_callers") for row in rows]


def callees(path: Path, branch_key: str, source_symbol_id: str) -> list[dict[str, Any]]:
    init_db(path)
    with closing(_connect(path)) as conn:
        edges = conn.execute(
            "SELECT * FROM code_edges WHERE branch_key=? AND source_symbol_id=? ORDER BY line",
            (branch_key, source_symbol_id),
        ).fetchall()
        out: list[dict[str, Any]] = []
        for edge in edges:
            if edge["target_symbol_id"]:
                target = symbol_by_id(path, str(edge["target_symbol_id"]))
                if target:
                    target.update(dict(edge))
                    target["control_context"] = _decode_context(edge["control_context_json"])
                    target["call_source"] = edge["source_text"]
                    target["score"] = 2.0 if edge["resolution_status"] == "resolved" else 0.5
                    target["retrieval_backend"] = "call_graph_callees"
                    out.append(target)
            else:
                out.append({
                    **dict(edge),
                    "symbol_name": edge["target_name"],
                    "qualified_name": edge["target_name"],
                    "symbol_kind": "unresolved_call",
                    "signature": "",
                    "path": "",
                    "language": "",
                    "start_line": edge["line"],
                    "end_line": edge["line"],
                    "text": "",
                    "score": 0.25,
                    "retrieval_backend": "call_graph_callees",
                    "control_context": _decode_context(edge["control_context_json"]),
                    "call_source": edge["source_text"],
                })
        return out


def _graph_row(row: sqlite3.Row, backend: str) -> dict[str, Any]:
    item = dict(row)
    item["symbol_name"] = item.pop("name")
    item["symbol_kind"] = item.pop("kind")
    item["score"] = 2.0 if item["resolution_status"] == "resolved" else 0.5
    item["retrieval_backend"] = backend
    item["control_context"] = _decode_context(item.get("control_context_json"))
    item["call_source"] = item.get("source_text")
    return item


def graph_path(path: Path, branch_key: str, source_ids: list[str], target_ids: set[str], max_depth: int = 8, max_nodes: int = 2000) -> dict[str, Any]:
    init_db(path)
    frontier: list[tuple[str, list[dict[str, Any]]]] = [(source_id, []) for source_id in source_ids]
    visited = set(source_ids)
    explored = 0
    with closing(_connect(path)) as conn:
        while frontier and explored < max_nodes:
            current, trace = frontier.pop(0)
            if current in target_ids:
                return {"status": "found", "path": trace, "explored_nodes": explored}
            if len(trace) >= max_depth:
                continue
            rows = conn.execute(
                """
                SELECT * FROM code_edges
                WHERE branch_key=? AND source_symbol_id=? AND resolution_status='resolved' AND target_symbol_id IS NOT NULL
                ORDER BY line
                """,
                (branch_key, current),
            ).fetchall()
            explored += 1
            for row in rows:
                target = str(row["target_symbol_id"])
                edge = dict(row)
                edge["control_context"] = _decode_context(edge.get("control_context_json"))
                edge["call_source"] = edge.get("source_text")
                if target in target_ids:
                    return {"status": "found", "path": trace + [edge], "explored_nodes": explored}
                if target not in visited:
                    visited.add(target)
                    frontier.append((target, trace + [edge]))
        return {
            "status": "not_found",
            "path": [],
            "explored_nodes": explored,
            "truncated": explored >= max_nodes,
        }


def reachable_graph(
    path: Path,
    branch_key: str,
    source_ids: list[str],
    *,
    max_depth: int = 5,
    max_nodes: int = 120,
    max_edges: int = 400,
) -> dict[str, Any]:
    """Return a bounded reachable structural graph from exact source symbols.

    Resolved calls are traversed. Ambiguous and unresolved edges are retained as
    evidence boundaries but are never guessed through. This makes the result
    useful for broad flow investigations without changing the conservative call
    graph semantics used by exact path/claim validation.
    """
    init_db(path)
    depth_limit = max(0, min(int(max_depth), 12))
    node_limit = max(1, min(int(max_nodes), 2000))
    edge_limit = max(1, min(int(max_edges), 5000))
    frontier: list[tuple[str, int]] = [(source_id, 0) for source_id in source_ids]
    seen: set[str] = set()
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    boundary_counts = {"resolved": 0, "ambiguous": 0, "unresolved": 0}
    truncated = False

    with closing(_connect(path)) as conn:
        while frontier:
            symbol_id, depth = frontier.pop(0)
            if symbol_id in seen:
                continue
            if len(seen) >= node_limit:
                truncated = True
                break
            seen.add(symbol_id)
            symbol = symbol_by_id(path, symbol_id)
            if symbol:
                nodes.append({
                    "symbol_id": symbol.get("symbol_id"),
                    "name": symbol.get("symbol_name") or symbol.get("name"),
                    "qualified_name": symbol.get("qualified_name"),
                    "kind": symbol.get("symbol_kind") or symbol.get("kind"),
                    "path": symbol.get("path"),
                    "start_line": symbol.get("start_line"),
                    "end_line": symbol.get("end_line"),
                    "language": symbol.get("language"),
                    "depth": depth,
                })
            if depth >= depth_limit:
                continue

            rows = conn.execute(
                """
                SELECT * FROM code_edges
                WHERE branch_key=? AND source_symbol_id=?
                ORDER BY line, edge_id
                """,
                (branch_key, symbol_id),
            ).fetchall()
            for row in rows:
                if len(edges) >= edge_limit:
                    truncated = True
                    break
                edge = dict(row)
                edge["control_context"] = _decode_context(edge.get("control_context_json"))
                edge.pop("control_context_json", None)
                edge["call_source"] = edge.pop("source_text", "")
                status = str(edge.get("resolution_status") or "unresolved")
                if status not in boundary_counts:
                    status = "unresolved"
                boundary_counts[status] += 1
                edges.append(edge)
                target_id = str(edge.get("target_symbol_id") or "")
                if status == "resolved" and target_id and target_id not in seen:
                    frontier.append((target_id, depth + 1))
            if truncated:
                break

    return {
        "status": "ok",
        "nodes": nodes,
        "edges": edges,
        "source_symbol_ids": list(source_ids),
        "max_depth": depth_limit,
        "explored_nodes": len(nodes),
        "edge_count": len(edges),
        "boundaries": boundary_counts,
        "truncated": truncated or bool(frontier),
        "rules": [
            "Only resolved edges are traversed.",
            "Ambiguous and unresolved calls are retained as explicit boundaries and are never guessed through.",
            "The graph is a static possible-flow model, not evidence that a runtime execution occurred.",
        ],
    }


def references_for_symbol(path: Path, symbol_id: str, kinds: Iterable[str] = ()) -> list[dict[str, Any]]:
    init_db(path)
    kinds = tuple(kinds)
    with closing(_connect(path)) as conn:
        sql = "SELECT * FROM code_references WHERE source_symbol_id=?"
        params: list[Any] = [symbol_id]
        if kinds:
            placeholders = ",".join("?" for _ in kinds)
            sql += f" AND reference_kind IN ({placeholders})"
            params.extend(kinds)
        sql += " ORDER BY line, column_no"
        rows = []
        for row in conn.execute(sql, params).fetchall():
            item = dict(row)
            item["control_context"] = _decode_context(item.get("control_context_json"))
            rows.append(item)
        return rows


def indexed_projects(root: Path) -> list[str]:
    projects = root / "workspace" / "projects"
    if not projects.exists():
        return []
    out: list[str] = []
    for project in sorted(projects.iterdir()):
        db = db_path(project)
        if not db.exists():
            continue
        init_db(db)
        with closing(_connect(db)) as conn:
            if conn.execute("SELECT 1 FROM code_index_state LIMIT 1").fetchone():
                out.append(project.name)
    return out


def chunk_by_id(path: Path, chunk_id: str) -> dict[str, Any] | None:
    init_db(path)
    with closing(_connect(path)) as conn:
        row = conn.execute(
            """
            SELECT c.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json, s.signature
            FROM code_chunks c JOIN code_files f ON f.file_id=c.file_id
            LEFT JOIN code_symbols s ON s.symbol_id=c.symbol_id
            WHERE c.chunk_id=?
            """,
            (chunk_id,),
        ).fetchone()
        return dict(row) if row else None


def symbol_chunks(path: Path, symbol_id: str) -> list[dict[str, Any]]:
    init_db(path)
    with closing(_connect(path)) as conn:
        rows = conn.execute(
            """
            SELECT c.*, f.project_id, f.repo_id, f.source_id, f.source_type, f.revision_key, f.revision_label, f.content_identity, f.branch_key, f.branch_name,
                   f.commit_sha, f.dirty, f.path, f.language, f.parser_id,
                   f.parse_mode, f.parse_status, f.diagnostics_json, s.signature
            FROM code_chunks c JOIN code_files f ON f.file_id=c.file_id
            LEFT JOIN code_symbols s ON s.symbol_id=c.symbol_id
            WHERE c.symbol_id=? ORDER BY c.chunk_part
            """,
            (symbol_id,),
        ).fetchall()
        return [dict(row) for row in rows]


def all_branches(path: Path) -> list[dict[str, Any]]:
    init_db(path)
    with closing(_connect(path)) as conn:
        return [dict(row) for row in conn.execute("SELECT * FROM code_index_state ORDER BY indexed_at DESC").fetchall()]
